# __  ___                            ____
# \ \/ | |_ _ __ ___ _ __ ___   ___ / ___|___  _ __ ___
#  \  /| __| '__/ _ | '_ ` _ \ / _ | |   / _ \| '__/ _ \
#  /  \| |_| | |  __| | | | | |  __| |__| (_) | | |  __/
# /_/\_\\__|_|  \___|_| |_| |_|\___|\____\___/|_|  \___|
#
# Configuration generated in version 1.0.0

no-modify: 100

# Metrics:
# This plugin uses the bStats metrics system. If you want your data not to be collected, you can disable this system here. 
# The following information is collected and sent to bstats.org:
#      Whether the server is in offline or online mode
#      The plugin version
#      The server version
#      The java version
#      The OS version/name and architecture
#      The location of your server
#      The core count for the CPU
#      The number of players online
#      The Metrics version
metrics: true

# Language:
# Sets the language of all plugin messages
# It is necessary to restart the server for it to take effect.
#
# Available languages:
# English: en
# Spanish: es
language: en
 
# Welcome:
# Welcome all the users that enter the server.
# You can use the placeholders of the plugin (https://github.com/XtremePlugins/XtremeCore/wiki) or all PlaceHolderAPI placeholders.
welcome:

  # This is the message that appears when you enter a server. 
  # It can contain server information such as the store, web page or whatever you want.
  message:

    # Enables or disables the welcome message
    enabled: true

    # Time the server waits to send the welcome message. (In ticks)
    wait: 10 # 20 Ticks = 1 Second

    # This is the message that will be sent to the players. Modify it to your liking, you can add or remove the lines you want.
    list:
    - '&5&m--------------------------------------'
    - ''
    - '        &5✦ &d&lWELCOME TO &nSERVERNAME&5 ✦'
    - '   &b✵ &fThe best server in all of minecraft &b✵'
    - ''
    - ' &d➦ &fStore: &bstore.servername.com'
    - ' &d➦ &fWeb: &bwww.servername.com'
    - ' &d➦ &fDiscord: &bdiscord.servername.com'
    - ''
    - '&5&m--------------------------------------'

  # Title that will be sent to the players when they join to the server.
  # (Does not work in versions lower than 1.12)
  title:

    #Enables or disables the welcome title.
    enabled: true

    # Time the server waits to send the welcome title. (In ticks)
    wait: 10 # 20 Ticks = 1 Second

    # Set the welcome title
    title: '&d&lServer Name'

    # Sets the welcome subtitle. Appears below the title
    subtitle: '&fwww.servername.com'

    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10

    #The time it takes for the title to stay on the screen. (In ticks)
    stay: 80

    #The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 10

  # Actionbar that is sent to the player when they join the server.
  actionbar:

    # Enables or disables the welcome actionbar.
    enabled: true

    # Time the server waits to send the welcome actionbar. (In ticks)
    wait: 10 # 20 Ticks = 1 Second

    # Message to appear in the welcome actionbar
    message: '&dWelcome to YourServer'

  # Announces to all players when a player joins or leaves.
  broadcast:

    # Announces to all players when a new player joins the game
    first_join:

      # Enable or disable this broadcast
      enabled: true

      # Message that will appear in this broadcast
      message: '&f%player_name% &dhas logged into the server for the first time. Welcome to the server!'

    # Announces to all players when a player joins.
    join:

      # Enable or disable this broadcast
      enabled: true

      # Message that will appear in this broadcast
      message: '&8[&a+&8] &a%player_name%'

    # Announces to all players when a player leaves.
    leave:

      #Enable or disable this broadcast
      enabled: true

      # Message that will appear in this broadcast
      message: '&8[&c-&8] &a%player_name%'

# Scoreboard:
# Sets the scoreboard (sidebar) that is sent to the player
scoreboard:

  # Enables or disables the scoreboard
  enabled: true

  # Every how many ticks will the scoreboard be updated
  ticks: 10

  # The title displayed at the very top of the scoreboard
  # WARNING! (Only for 1.12 or earlier) The title must be 35 characters or less. (Including color codes).
  title: '&d&lXtreme &5&lCore'

  # The lines of the scoreboard. (Maximum 15 lines)
  lines: 
  - '&a'
  - '&d&l➦ Player Name'
  - ' &b● &f%player_name%'
  - '&b'
  - '&d&l➦ Ping'
  - ' &b● &f%player_ping%'
  - '&c'
  - '&d&l➦ Money'
  - ' &b● &f%player_money%'
  - '&d'
  - 'play.servername.com'
  

  disabled-worlds:
  - 'world_the_end'

# TabList:
# Sets the header and footer in the player list. (Show when you press the TAB key)
tablist:

  # Enable or disable the tablist
  enabled: true

  # Every how many ticks will the tablist be updated 
  ticks: 10

  # Sets the header of the tablist. Add or remove the lines you want.
  header:
  - ''
  - '&d&lXtremeCore'
  - '&fwww.servername.com'
  - ''

  # Sets the footer of the tablist. Add or remove the lines you want.
  footer:
  - ''
  - '&7You are playing with &d%online% players'
  - '&7                                                  &7'
  
# Chat:
# Customize your server chat.
chat:

   # Customize the format of your server chat.
   # If you prefer to disable this option and use the original format of minecraft or another plugin write 'none'.
   format: '&7%player_displayname% &8➤ &f%message%'
   
   # If you enable this option, players will only be able to read messages from other players who are in the same world.
   per_world: false
   
   # Avoid toxicity on your server by blocking bad vocabulary
   antiswear:
   
      # Enables or disables the antiswear.
      enabled: true
      
      # What do you want to happen if a blocked word is detected?
      # - Block the whole message. (mode: block)
      # - Replace the blocked word with asterisks (mode: replace)
      mode: replace
      
      # List of blocked words. You can add or remove the ones you want.
      list:
      - 'asshole'
      - 'bitch'
      - 'cunt'
      - 'dick'
      - 'fuck'
      - 'loser'
      - 'idiot'
      
   # Block commands that can generate security vulnerabilities in your server.
   command_blocker:
   
      # Enables or disables the command blocker
      enabled: true
      
      # List of blocked commands (You have to include the /)
      list:
      - '/pl'
      - '/plugins'