name: BlueCore
version: 1.0.0
main: net.blueva.core.Main
author: Blueva
description: Everything you need for your server is in this plugin.
api-version: 1.21
load: STARTUP
website: blueva.net
softdepend:
   - PlaceholderAPI
   - Vault
libraries:
   - 'dev.dejvokep:boosted-yaml:1.3.7'
   - 'org.spongepowered:configurate-gson:4.2.0'
   - 'net.kyori:adventure-api:4.25.0'
   - 'net.kyori:adventure-text-minimessage:4.25.0'
   - 'net.kyori:adventure-platform-bukkit:4.4.1'
   - 'fr.mrmicky:fastboard:2.1.5'
   - 'org.mvel:mvel2:2.5.2.Final'
commands:
   bluecore:
      aliases: [ bc, bcore, bluec, core ]
      description: Main command
      usage: /bluecore [action]