name: BlueCore
version: 1.0.0
main: net.blueva.core.Main
author: Blueva
description: Everything you need for your server is in this plugin.
api-version: 1.19
load: STARTUP
website: blueva.net
softdepend:
   - PlaceholderAPI
   - Vault
commands:
   adventure:
      aliases: [ badventure, adven, adv, a, gma ]
      description: Change your game mode
      usage: /adventure [action]
   clearchat:
      aliases: [ bclearchat, ncc, cc ]
      description: Clears the chat of one or all players
      usage: /clearchat [action]
   createkit:
      aliases: [ bcreatekit, ck ]
      description: Create a new kit on the server.
      usage: /createkit [action]
   bluecore:
      aliases: [ bc, bcore, bluec, core ]
      description: Main command
      usage: /bluecore [action]
   creative:
      aliases: [ bcreative, crea, cr, c, gmc ]
      description: Change your game mode
      usage: /creative [action]
   day:
      aliases: [ nday ]
      description: Change the world time to day
      usage: /day [action]
   deletewarp:
      aliases: [ bdeletewarp, bdelwarp, delwarp ]
      description: Deletes a warp
      usage: /deletewarp [action]
   enderchest:
      aliases: [ benderchest, bec, ec ]
      description: Open the Ender Chest
      usage: /enderchest [action]
   feed:
      aliases: [ bfeed, beat, eat ]
      description: Satisfy the hunger.
      usage: /feed [action]
   fly:
      aliases: [ bfly ]
      description: Activate fly mode.
      usage: /fly [action]
   gamemode:
      aliases: [ bgamemode, bgm, gm, gmode, gamem ]
      description: Change your game mode
      usage: /gamemode [action]
   god:
      aliases: [ bgod ]
      description: Enable god mode
      usage: /god [action]
   heal:
      aliases: [ bheal ]
      description: Heals you or the given player.
      usage: /heal [action]
   kill:
      aliases: [ bkill, murder ]
      description: Kill a player
      usage: /kill [action]
   kit:
      aliases: [ bkit, kits ]
      description: Receive or give a kit.
      usage: /kit [action]
   midnight:
      aliases: [ bmidnight ]
      description: Change the world time to midnight
      usage: /midnight [action]
   modifykit:
      aliases: [ bmodifykit, modifyk ]
      description: Modify a kit already created
      usage: /modifykit [action]
   night:
      aliases: [ bnight ]
      description: Change the world time to night
      usage: /night [action]
   noon:
      aliases: [ bnoon ]
      description: Change the world time to noon
      usage: /noon [action]
   setspawn:
      aliases: [ bsetspawn ]
      description: Sets the spawn
      usage: /setspawn [action]
   setwarp:
      aliases: [ bsetwarp ]
      description: Sets a warp
      usage: /setwarp [action]
   spawn:
      aliases: [ bspawn ]
      description: Teleport to the spawn
      usage: /spawn [action]
   spectator:
      aliases: [ bspectator, spec, sp, gmsp ]
      description: Change your game mode
      usage: /spectator [action]
   speed:
      aliases: [ bspeed ]
      description: Change your speed
      usage: /spectator [action]
   storm:
      aliases: [ bstorm, brain, rain]
      description: Change the climate from one world to storm
      usage: /storm [action]
   sudo:
      aliases: [ bsudo, bexecute, execute]
      description: Execute a command through another player.
      usage: /sudo [action]
   suicide:
      aliases: [ bsuicide ]
      description: Kill yourself
      usage: /suicide [action]
   sun:
      aliases: [ bsun, bclear, clear ]
      description: Change the climate from one world to clear
      usage: /sun [action]
   teleport:
      aliases: [ bteleport, tp, goto ]
      description: Teleport to a player or location.
      usage: /teleport [action]
   survival:
      aliases: [ bsurvival, surv, srv, s, gms ]
      description: Change your game mode
      usage: /survival [action]
   updatewarp:
      aliases: [ bupdatewarp, bupdwarp, updwarp ]
      description: Update a warp
      usage: /updatewarp [action]
   warp:
      aliases: [ bwarp ]
      description: Teleport to a warp
      usage: /warp [action]
   workbench:
      aliases: [ bworkbench, bwb, bcraftingtable, bcraft, wb, craftingtable, craft ]
      description: Open the Crafting Table
      usage: /workbench [action]
   world:
      aliases: [ bworld, worlds, wm, w ]
      description: Manage your server worlds
      usage: /world [action]