name: TheNexus
version: 1.0.0
main: org.jachi.whirss.thenexus.Main
author: Whirss
load: STARTUP
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
   nexus:
      aliases: [thenexus, tn, nx, x]
      description: Command for players
      usage: /nexus [action]
   worldmanager:
      aliases: [ world, worlds, wm, w ]
      description: World Manager
      usage: /worldmanager [action]