name: TheNexus
version: 1.0.0
main: org.jachi.whirss.thenexus.Main
author: Whirss
api-version: 1.17
load: STARTUP
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
   adventure:
      aliases: [ nadventure, adven, adv, a, gma ]
      description: Change your game mode
      usage: /adventure [action]
   clearchat:
      aliases: [ nclearchat, ncc, cc ]
      description: Clears the chat of one or all players
      usage: /clearchat [action]
   creative:
      aliases: [ ncreative, crea, cr, c, gmc ]
      description: Change your game mode
      usage: /creative [action]
   deletewarp:
      aliases: [ ndeletewarp, ndelwarp, delwarp ]
      description: Deletes a warp
      usage: /deletewarp [action]
   enderchest:
      aliases: [ nenderchest, nec, ec ]
      description: Open the Ender Chest
      usage: /enderchest [action]
   feed:
      aliases: [ nfeed, neat, eat ]
      description: Satisfy the hunger.
      usage: /feed [action]
   fly:
      aliases: [ nfly ]
      description: Activate fly mode.
      usage: /fly [action]
   gm:
      aliases: [ ngamemode, ngm, gmode, gamem ]
      description: Change your game mode
      usage: /gm [action]
   god:
      aliases: [ ngod ]
      description: Enable god mode
      usage: /god [action]
   heal:
      aliases: [ nheal ]
      description: Heals you or the given player.
      usage: /heal [action]
   nexus:
      aliases: [ thenexus, tn, nx, x ]
      description: Command for players
      usage: /nexus [action]
   setspawn:
      aliases: [ nsetspawn ]
      description: Sets the spawn
      usage: /setspawn [action]
   setwarp:
      aliases: [ nsetwarp ]
      description: Sets a warp
      usage: /setwarp [action]
   spawn:
      aliases: [ nspawn ]
      description: Teleport to the spawn
      usage: /spawn [action]
   spectator:
      aliases: [ nspectator, spec, sp, gmsp]
      description: Change your game mode
      usage: /spectator [action]
   survival:
      aliases: [ nsurvival, surv, srv, s, gms ]
      description: Change your game mode
      usage: /survival [action]
   updatewarp:
      aliases: [ nupdatewarp, nupdwarp, updwarp ]
      description: Update a warp
      usage: /updatewarp [action]
   warp:
      aliases: [ nwarp ]
      description: Teleport to a warp
      usage: /warp [action]
   worldmanager:
      aliases: [ nworld, world, worlds, wm, w ]
      description: World Manager
      usage: /worldmanager [action]